import React from 'react';
import styles from '@/styles/ESD-Access-Control/BenefitsSection.module.css';
import Image from 'next/image';

const BenefitsSection = () => {
  const benefits = [
    'Fully automatic ESD turnstile gate access control, no chance of errors.',
    'Only registered users will get access to ESD Protected Area or production Floor.',
    'No chance of product damages because of Human ESD shock.',
    'Increases product quality, zero on field product failure, no product complaints, happy customers.',
    'High Quality Product results gain of business and revenue.',
    'No entry to unauthorized user on Production floor.',
    'Register user will only get access to EPA, if ESD testing is PASS.',
    'Complete records of ESD test done by employees that can be used for several purposes.',
    'Reports and logs generated by ESD access control system can be use in ESD Audit process of production floor.',
    'Self automatic error diagnostic by ESD gate / ESD turnstile / ESD Tripod access control system.',
    'Client will be happy and impressed to see automatic ESD access control system on production floor.',
    'ESD access control system is completely customized solution that can fulfill each ESD Protected Area.'
  ];

  return (
    <section className={styles.benefitsSection}>
      <div className={styles.container}>
        <h2 className={styles.sectionTitle}>Benefits of ESD Turnstile Access Control System</h2>
        <div className={styles.benefitsContainer}>
          <div className={styles.benefitsList}>
            <ol className={styles.benefitsOl}>
              {benefits.map((benefit, index) => (
                <li key={index} className={styles.benefitItem}>
                  <span className={styles.benefitNumber}>{index + 1}.</span>
                  <span className={styles.benefitText}>{benefit}</span>
                </li>
              ))}
            </ol>
          </div>
          <div className={styles.benefitImage}>
            <Image
              src="/images/SecureAccessManagement/ESDAccessControlSystemBenefits.webp"
              alt="ESD Access Control System Benefits"
              width={500}
              height={600}
              layout="responsive"
              className={styles.image}
            />
          </div>
        </div>
      </div>
    </section>
  );
};

export default BenefitsSection;
