

import React from 'react';
import styles from '@/styles/BarcodeCardAccess/BenefitsSection.module.css';
import Image from 'next/image';

const benefits = [
  {
    id: 1,
    title: 'Numerous Credentials',
    description: 'Choose QR Code / Cards controls',
    icon: '/images/SecureAccessManagement/Barcode access Management/numerous_credential.png'
  },
  {
    id: 2,
    title: 'Quick & Accurate',
    description: 'Each verification takes less than 0.2 seconds with accurate results',
    icon: '/images/SecureAccessManagement/Barcode access Management/Quick_Accurate.png'
  },
  {
    id: 3,
    title: 'Safe & Secure',
    description: 'Secure Validation Engine to process all the access requests',
    icon: '/images/SecureAccessManagement/Barcode access Management/Safe_Secure.png'
  },
  {
    id: 4,
    title: 'Scalable',
    description: 'Multiple Access gates and control box can be added to scale control',
    icon: '/images/SecureAccessManagement/Barcode access Management/Scalable.png'
  },
  {
    id: 5,
    title: 'Smart Software Control',
    description: 'Smart Software Features to control the access control system',
    icon: '/images/SecureAccessManagement/Barcode access Management/Smart Software Control.png'
  },
  {
    id: 6,
    title: 'Visitor Pass',
    description: 'Single Entry / Exit Access visitor pass',
    icon: '/images/SecureAccessManagement/Barcode access Management/Visitor Pass.png'
  },
  {
    id: 7,
    title: 'Low Cost Solution',
    description: 'User can use their Phone to get access to save papers',
    icon: '/images/SecureAccessManagement/Barcode access Management/Low-Cost-Solution.png'
  },
  {
    id: 8,
    title: 'Admin Reports',
    description: 'Several types of reports can be generated by Access Control Software',
    icon: '/images/SecureAccessManagement/Barcode access Management/Admin Reports.png'
  }
];

const BenefitsSection = () => {
  return (
    <section className={styles.benefitsSection}>
      <div className={styles.container}>
        <h2 className={styles.sectionTitle}>Benefits of QRcode Access Control System</h2>
        <div className={styles.benefitsGrid}>
          {benefits.map((benefit) => (
            <div key={benefit.id} className={styles.benefitCard}>
              <div className={styles.iconContainer}>
                <Image
                  src={benefit.icon}
                  alt={benefit.title}
                  width={60}
                  height={60}
                  className={styles.benefitIcon}
                />
              </div>
              <h3 className={styles.benefitTitle}>{benefit.title}</h3>
              <p className={styles.benefitDescription}>{benefit.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default BenefitsSection;
