

import React from 'react';
import Image from 'next/image';
import styles from '@/styles/BarcodeCardAccess/QrCodeAccessSystem.module.css';

const QrCodeAccessSystem = () => {
  return (
    <section className={styles.qrCodeSection}>
      <div className={styles.container}>
        <h2 className={styles.sectionTitle}>QR Code Access Control System</h2>
        
        <div className={styles.solutionsGrid}>
          {/* Visitor QR Code Access Control System */}
          <div className={styles.solutionCard}>
            <div className={styles.solutionContent}>
              <h3 className={styles.solutionTitle}>How Visitor QR Code Access Control System Works</h3>
              <ul className={styles.featureList}>
                <li className={styles.featureItem}>Visitor shares their details and purpose of visit with the front desk attendant (Name, location, Identity, Photo, whom to meet, purpose, etc.)</li>
                <li className={styles.featureItem}>Secure unique visitor pass generated and printed automatically by VMS software</li>
                <li className={styles.featureItem}>Visitor pass is valid for one entry and exit to premises for specific duration of time</li>
                <li className={styles.featureItem}>Visitor shows their QR code printed on Pass to Access Control System</li>
                <li className={styles.featureItem}>QR code Access Control System verifies the pass at connected server</li>
                <li className={styles.featureItem}>At exit, visitor has to submit the visitor pass at exit and pass should be signed by person whom the visitor met</li>
                <li className={styles.featureItem}>Several types of reports can be generated by VMS Software</li>
                <li className={styles.featureItem}>On demand customized features can also be implemented</li>
              </ul>
            </div>
            <div className={styles.solutionImage}>
              <Image
                src="/images/SecureAccessManagement/Barcode access Management/How Visitor QRcode Access Control System Works.png"
                alt="Visitor QR Code Access Flow"
                width={500}
                height={500}
                className={styles.image}
              />
            </div>
          </div>

          {/* Employee QR Code Access Control System */}
          <div className={`${styles.solutionCard} ${styles.reverse}`}>
            <div className={styles.solutionContent}>
              <h3 className={styles.solutionTitle}>How Employee QR Code Access Control System Works</h3>
              <ul className={styles.featureList}>
                <li className={styles.featureItem}>One time registration of employees in QR Code Access Control System</li>
                <li className={styles.featureItem}>Unique and Secure QR code generated for each employee</li>
                <li className={styles.featureItem}>Mobile Application for employee to get personal unique QR code or Printed QR code can be used to get access</li>
                <li className={styles.featureItem}>On Entry/Exit user will show their personal QR code to Access Control system</li>
                <li className={styles.featureItem}>Access Control system validates the user (online/offline) and grants access if valid</li>
                <li className={styles.featureItem}>All the entry and exit records are available in SQL Server</li>
                <li className={styles.featureItem}>Several types of access control policies can be applied on the access gates for user groups</li>
                <li className={styles.featureItem}>Administrative reports are available for administrative use</li>
                <li className={styles.featureItem}>On demand customized features can also be implemented</li>
              </ul>
            </div>
            <div className={styles.solutionImage}>
              <Image
                src="/images/SecureAccessManagement/Barcode access Management/How Employee QRcode Access Control System Works.jpg"
                alt="Employee QR Code Access Flow"
                width={500}
                height={500}
                className={styles.image}
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default QrCodeAccessSystem;
